# Generated by Django 5.1.4 on 2025-01-06 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wards',
            name='capacity',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='wards',
            name='capacity_en',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='wards',
            name='capacity_tr',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='wards',
            name='current_occupancy',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='wards',
            name='current_occupancy_en',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='wards',
            name='current_occupancy_tr',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='wards',
            name='ward_type',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='wards',
            name='ward_type_en',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='wards',
            name='ward_type_tr',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
