# Generated by Django 5.1.4 on 2025-01-06 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_doctors_doctor_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctors',
            name='user_en',
        ),
        migrations.RemoveField(
            model_name='doctors',
            name='user_tr',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='user_en',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='user_tr',
        ),
        migrations.AddField(
            model_name='hospital',
            name='doctor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='clinic.doctors'),
            preserve_default=False,
        ),
    ]
