# Generated by Django 5.1.4 on 2025-01-06 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0005_remove_doctors_user_en_remove_doctors_user_tr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospitals', to='clinic.hospital'),
        ),
    ]
