# Generated by Django 5.1.4 on 2025-01-07 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0007_hospital_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospitals', to='clinic.doctors'),
        ),
        migrations.DeleteModel(
            name='Hospital',
        ),
    ]
